### ISSUE TITLE
RecommendDetailContentsOrganism 내의 tag 안나옴 문제

### ISSUE THREAD

**Issue by ShinJongUng** [dnd-side-project/dnd-7th-6-frontend#70]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/65454966/182137589-b4098b73-f5aa-44ce-8356-defc3f1eeca1.png">
tag -> title로 이름 바뀌었답니다.. ㅋㅋㅋ 수정부탁드려요 기한님

**Comment by vgihan** [comment]
해결했습니당 close 할게요 ~
